services:
  db:
    image: postgres:15-alpine
    container_name: task_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: task_api
    volumes:
      - ./app:/src/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/task_db
    depends_on:
      - db

volumes:
  db_data:
